# Multi Stage build
version: '3.9'
services:
  db:
    build:
        context: .
        dockerfile: Dockerfile.database
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spring-test-api
    volumes:
      - ./data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: spring-app-build
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/spring-test-api
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - .:/app
      - ~/.m2:/root/.m2 # Caching the maven dependencies
