# Use the `eclipse-temurin:17-jdk-alpine` image as the base image for this container
FROM eclipse-temurin:17-jdk-alpine AS build

# Update the package index and install the `inotify-tools` package
RUN apk update && \
    apk add inotify-tools git curl

# Set the working directory for the container to `/app`
WORKDIR /app

# Copy the `.mvn/` directory, `mvnw` file and `pom.xml` file from the local machine to the container
COPY .mvn/ .mvn
COPY mvnw pom.xml ./

# Make the `mvnw` file executable
RUN chmod +x mvnw
# RUN chmod +x mvnw && ./mvnw dependency:go-offline # Download the maven dependency in the container

# Copy the `src/` directory from the local machine to the container
COPY src ./src

# Set the entrypoint for the container to be `./mvnw spring-boot:run`
ENTRYPOINT ["./mvnw", "spring-boot:run"]

# Expose port 8080 on the container
EXPOSE 8080
